const mongoose = require('mongoose');

const PremioNobelSchema = mongoose.Schema({
    awardYear:{
        type:String
    },
    category:{
        en:{
            type:String
        },
        no:{
            type:String
        },
        se:{
            type:String
        }
    },
    categoryFullName:{
        en:{
            type:String
        },
        no:{
            type:String
        },
        se:{
            type:String
        }
    },
    prizeAmount:{
        type:Number
    },
    prizeAmountAdjusted:{
        type:Number
    },
    links:{
        rel:{
            type:String
        },
        href:{
            type:String
        },
        action:{
            type:String
        },
        types:{
            type:String
        }
    },
    category:{
        en:{
            type:String
        },
        no:{
            type:String
        },
        se:{
            type:String
        }
    },
    laureates:{
        type:Array,
        id:{
            type:String
        },
        knownName:{
            en:{
                type:String
            }
        },
        portion:{
            type:String
        },
        sortOrder:{
            type:String
        },
        motivation:{
            en:{
                type:String
            },
            no:{
                type:String
            }
        },
        links:{
            rel:{
                type:String
            },
            href:{
                type:String
            },
            action:{
                type:String
            },
            types:{
                type:String
            }
        }
    }
})

exports.Premio = mongoose.model('premioNobel',PremioNobelSchema);